export enum ConfigKeys {
  TG_TOKEN = "TG_TOKEN",
  POSTGRES_DB = "POSTGRES_DB",
  POSTGRES_USER = "POSTGRES_USER",
  POSTGRES_PASSWORD = "POSTGRES_PASSWORD",
  POSTGRES_PORT = "POSTGRES_PORT",
  USER_AGENT = "USER_AGENT",
}
